Use strongly type enum for key status. Handle standard...
... events into getPressedKeys.
Also rename enum values to avoid following error (probably because
KEY_UNKNOWN is already defined somewhere).

../../../../src/bin/daemon/keyboard_driver.h:47:2: error: expected
identifier before numeric constant
  KEY_UNKNOWN