Qt gui: fix deprecation warning
> ../src/bin/gui/Qt/LCDPluginsTab.cpp: In member function 'virtual void
GLogiK::LCDPluginsTab::updateTab(const GLogiK::DeviceProperties&, const
std::string&)':
> ../src/bin/gui/Qt/LCDPluginsTab.cpp:182:72: error: 'void
QCheckBox::stateChanged(int)' is deprecated: Use checkStateChanged()
instead [-Werror=deprecated-declarations]
>   182 |   QObject::connect(checkbox, &QCheckBox::stateChanged, this,
            &LCDPluginsTab::updateNewLCDPluginsMask);
>       |
^~~~~~~~~~~~
> compilation terminated due to -Wfatal-errors.
> cc1plus: all warnings being treated as errors

https://doc.qt.io/qt-6/qcheckbox.html#stateChanged

> This function is scheduled for deprecation in version 6.9.
>
> Use checkStateChanged(Qt::CheckState) instead.

Signed-off-by: Fabrice Delliaux <netbox253@gmail.com>