Fix build error after commit ee1f10a.
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/home/netfab/dev/projects/GLogiK/tools/.. -I/home/netfab/dev/projects/GLogiK/tools/../src -Wall -Werror -Wfatal-errors -std=c++14 -I/usr/include -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wformat=2 -MT src/lib/shared/libGKShared_la-deviceProperties.lo -MD -MP -MF src/lib/shared/.deps/libGKShared_la-deviceProperties.Tpo -c /home/netfab/dev/projects/GLogiK/tools/../src/lib/shared/deviceProperties.cpp  -fPIC -DPIC -o src/lib/shared/.libs/libGKShared_la-deviceProperties.o
In file included from /home/netfab/dev/projects/GLogiK/tools/../src/lib/shared/deviceProperties.cpp:22:
/home/netfab/dev/projects/GLogiK/tools/../src/include/enums.hpp: In function 'GLogiK::Caps GLogiK::operator|(GLogiK::Caps, GLogiK::Caps)':
/home/netfab/dev/projects/GLogiK/tools/../src/include/enums.hpp:108:17: error: 'underlying_type_t' in namespace 'std' does not name a template type
  using T = std::underlying_type_t<Caps>;
                 ^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [Makefile:1736: src/lib/shared/libGKShared_la-deviceProperties.lo] Error 1
make[2]: *** Waiting for unfinished jobs....

This popup because <stdexcept> include was removed from src/lib/shared/deviceProperties.cpp.