Fix linking error: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
Pops up on archlinux.

libtool: link: g++ -std=gnu++14 -I/usr/include -I/usr/include/dbus-1.0
-I/usr/lib/dbus-1.0/include -Wall -Werror -Wfatal-errors -std=c++14 -O2
-pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wformat=2 -Wl,--as-needed
-o .libs/GKsLauncher src/bin/launcher/GKsLauncher-main.o
src/bin/launcher/GKsLauncher-DBusHandler.o
src/bin/launcher/GKsLauncher-launcher.o  -L/usr/lib64
-lboost_program_options ./.libs/libGKDBus.so -ldbus-1
./.libs/libGKUtils.so ./.libs/libGKShared.so -lSM -lICE
-lboost_serialization /var/tmp/devcxx/build/.libs/libGKUtils.so
-lboost_system -lboost_filesystem -Wl,-rpath
-Wl,/var/tmp/devcxx/GLogiK/lib
/usr/bin/ld: src/bin/launcher/GKsLauncher-DBusHandler.o: undefined
reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libpthread.so.0: error adding symbols: DSO missing
from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1364: GKsLauncher] Error 1
make[2]: *** Waiting for unfinished jobs....